### PR TITLE
Agent supports reconnect

### LINKED ISSUE #21: Make sure proxy-agent reconnects to the proxy-server.
Make sure we handle cases like the proxy-agent coming up before the proxy-server. Also it should reconnect if the connection is broken. We should also have tests for this.

### PR DESCRIPTION
**Pull request by anfernee**
When the dialback is interrupted, the agent connects back to the proxy
server and continue to serve the proxy requests.

Fixes #21

The change also adds integration test for basic proxy functionality
    - The test covers both grpc and http-connect
    - The remote server is http based, so it won't send traffic volunteerly
      unless there is a request
    - The test traffic is not over TLS

### CODE REVIEW

**Comment by yamt** [comment]
isn't grpc.Dial asynchronous by default?
i thought it dealt with reconnect by itself as well.

**Comment by anfernee** [comment]
@yamt [dial](https://godoc.org/google.golang.org/grpc#Dial) doesn't seem to redial, it just returns a Conn

File: Makefile [hunk 1]
```diff
@@ -1,5 +1,8 @@
 # Copyright 2019 The Kubernetes Authors.
 #
+#test:
```
Comment (cheftako) [inline Makefile]: These 3 lines do no seem correct.

File: pkg/agent/agentclient/stream.go [hunk 2]
```diff
@@ -0,0 +1,156 @@
...
+		klog.Info("start reconnecting")
+
+		if err2 := c.reconnect(); err2 != nil {
+			klog.Infof("reconnect failed: %v", err2)
+			return pkt, err2
+		}
+
+		return c.stream.Recv()
+	} else {
+		return pkt, err
```
Comment (cheftako) [inline pkg/agent/agentclient/stream.go]: Shouldn't err be nil here? Seems more clear to return pkt, nil

File: pkg/agent/agentclient/stream.go [hunk 3]
```diff
@@ -0,0 +1,156 @@
...
+
+	for retry < c.Retry {
+		if err = c.tryConnect(); err == nil {
+			klog.Info("connected")
+			return nil
+		}
+		retry++
+		klog.V(5).Infof("Failed to connect to proxy server, retry %d in %v: %v", retry, c.Interval, err)
+		klog.Infof("Failed to connect to proxy server, retry %d in %v: %v", retry, c.Interval, err)
+		time.Sleep(c.Interval)
```
Comment (cheftako) [inline pkg/agent/agentclient/stream.go]: We are sleeping while holding a lock. Wondering if we always want to block everyone here. Please note that this can lead to arbitrarily long waits. For things like probe we may want it to fail faster.

File: pkg/agent/agentclient/stream.go [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+	} else {
+		return pkt, err
+	}
+}
+
+func (c *RedialableAgentClient) reconnect() error {
+	c.reconnLock.Lock()
+	defer c.reconnLock.Unlock()
+
+	if c.conn != nil && c.conn.GetState() == connectivity.Ready {
```
Comment (cheftako) [inline pkg/agent/agentclient/stream.go]: Why is this connectivity check inside the reconnLock, the send connectivity check in the sendLock and the probe connectivity check not in a lock at all?

File: pkg/agent/agentclient/stream.go (hunk 3 above)
Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: the lock is to prevent concurrent reconnect. but you are right, we should trigger reconnect in probe instead of direct calling it.

File: pkg/agent/agentclient/stream.go (hunk 4 above)
Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: This is a bit confusing, I refactor a little bit to clear it up.

**Comment by anfernee** [comment]
@cheftako updated. not exactly sure what's wrong with commit message tho.

**Comment by cheftako** [comment]
Have we thought through the client behaviors in various error cases? A few that come to mind, what if the client attempts to connect to a hostname which will not DNS resolve? What if nothing is listening on the relevant port, will we eventually give up and give back an error?

**Comment by anfernee** [comment]
@cheftako that's a good point. we could differentiate "transient" errors from those that are not. the only non-transient error now is `EOF`. We retry all others, which I think it's fine. If nothing listens on a given port, we still retry until the port is open, this will survive server crash and come back.

**Comment by cheftako** [comment]
So I think we should either extend our non transient error support or file a bug to handle it. If we misconfigure the client to connect to the proxy server which is not reachable (eg bad hostname or any other "permenant" error), I think we should blow up loudly and immediately to ease debugging.

We should also discuss how to handle "permenant" transient errors. If there is something sufficiently wrong with an agent that happens to surface as a transient error (Eg. wrong port number for the proxy server). I think we should eventually escalate the error. Obviously we could accomplish that through the healthcheck... We again should either fix it here or file a bug to track that work needs to be done.

File: pkg/agent/agentclient/stream.go [hunk 5]
```diff
@@ -0,0 +1,203 @@
...
+	go c.reconnect()
+
+	return c.reconnTrigger
+}
+
+func (c *RedialableAgentClient) doneReconnect(err error) {
+	c.reconnLock.Lock()
+	defer c.reconnLock.Unlock()
+
+	c.reconnTrigger <- err
```
Comment (cheftako) [inline pkg/agent/agentclient/stream.go]: I have some concerns about what happens when we have multiple clients with the channel.
Please see https://play.golang.org/p/iKP5oETRahJ.
As far as I can tell we ONLY awake the first listener on a given channel instance.

**Comment by anfernee** [comment]
How about we doing this: when agent starts, we do `connect` and treat all errors critical. After that, we `reconnect` on failed connection.

File: pkg/agent/agentclient/stream.go (hunk 5 above)
Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: seems like a bug. the the chan needs to be closed.

Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: the error msg chan needs to go thru a 1:n fanout basically. good catch.

File: pkg/agent/agentclient/stream.go [hunk 6]
```diff
@@ -0,0 +1,213 @@
...
+	internalErr error
+	errChan     <-chan error
+}
+
+func (e *ReconnectError) Error() string {
+	return "transient error: " + e.internalErr.Error()
+}
+
+func (e *ReconnectError) Wait() error {
+	return <-e.errChan
```
Comment (cheftako) [inline pkg/agent/agentclient/stream.go]: So I see code reading from the error channel but nothing writing to it?

Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: it's queued in `reconnWaiters`, and `doneReconnect()` writes to all the waiters channels.

File: pkg/agent/agentclient/stream.go [hunk 7]
```diff
@@ -0,0 +1,213 @@
...
+
+	return errch
+}
+
+func (c *RedialableAgentClient) doneReconnect(err error) {
+	c.reconnLock.Lock()
+	defer c.reconnLock.Unlock()
+
+	for _, ch := range c.reconnWaiters {
+		ch <- err
```
Comment (anfernee) [inline pkg/agent/agentclient/stream.go]: this is where it writes to.

File: pkg/agent/agentclient/stream.go (hunk 6 above)
Comment (cheftako) [reply pkg/agent/agentclient/stream.go]: Sorry missed that. That leaves me with the question where is it closed?

Comment (anfernee) [reply pkg/agent/agentclient/stream.go]: it's not closed. if it is not used, it will be gc'ed by system.

**Comment by justinsb** [comment]
As far as I can tell, this is the default GRPC behaviour: https://grpc.io/blog/grpc_on_http2/

Is there a link to the GRPC bug that we're working around here?

**Comment by anfernee** [comment]
@justinsb We use a bi-directional stream on top of the gRPC connection. When the connection is down, we need to reset the stream as well: https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/pkg/agent/agentclient/stream.go#L209
