### PR TITLE
add CI and fix code to pass linting

### LINKED ISSUE #3: Enable basic CI
- Run unit test
- golint

### PR DESCRIPTION
**Pull request by Sh4d1**
Fixes #3 

Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

File: pkg/agent/agentserver/tunnel.go [hunk 1]
```diff
@@ -121,7 +121,10 @@ func (t *Tunnel) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 				},
 			},
 		}
-		t.Server.Backend.Send(packet)
+		err = t.Server.Backend.Send(packet)
+		if err != nil {
+			klog.Errorf("Error sending packet %v", err)
```
Comment (cheftako) [inline pkg/agent/agentserver/tunnel.go]: Might want to continue here. It would prevent any confusion from logging about the packet having been (successfully) forwarded.

Comment (Sh4d1) [reply pkg/agent/agentserver/tunnel.go]: :+1:

File: pkg/agent/agentserver/tunnel.go [hunk 2]
```diff
@@ -121,7 +121,11 @@ func (t *Tunnel) ServeHTTP(w http.ResponseWriter, r *http.Request) {
...
```
Comment (cheftako) [inline pkg/agent/agentserver/tunnel.go]: Sorry should have caught this before. Errors should start with a lower case letter.

Comment (Sh4d1) [reply pkg/agent/agentserver/tunnel.go]: Fixed

**Comment by cheftako** [comment]
If no objection in the next day, I will go ahead and merge.
